//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class NodeosSwigLoggerModulePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="SWIGRegisterExceptionCallbacks_NodeosSwigLoggerModule")]
    public static extern void SWIGRegisterExceptionCallbacks_NodeosSwigLoggerModule(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_NodeosSwigLoggerModule")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_NodeosSwigLoggerModule(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_NodeosSwigLoggerModule(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_NodeosSwigLoggerModule(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="SWIGRegisterStringCallback_NodeosSwigLoggerModule")]
    public static extern void SWIGRegisterStringCallback_NodeosSwigLoggerModule(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_NodeosSwigLoggerModule(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static NodeosSwigLoggerModulePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_swig_logger_base")]
  public static extern void delete_swig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_deep_mind_version")]
  public static extern void swig_logger_base_on_deep_mind_version(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_deep_mind_versionSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_deep_mind_versionSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_abidump_start")]
  public static extern void swig_logger_base_on_abidump_start(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_abidump_startSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_abidump_startSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_abidump_abi")]
  public static extern void swig_logger_base_on_abidump_abi(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_abidump_abiSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_abidump_abiSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_abidump_end")]
  public static extern void swig_logger_base_on_abidump_end(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_abidump_endSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_abidump_endSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_start_block")]
  public static extern void swig_logger_base_on_start_block(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_start_blockSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_start_blockSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_accepted_block")]
  public static extern void swig_logger_base_on_accepted_block(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_accepted_blockSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_accepted_blockSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_switch_forks")]
  public static extern void swig_logger_base_on_switch_forks(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_switch_forksSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_switch_forksSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_error")]
  public static extern void swig_logger_base_on_error(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_errorSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_errorSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_onblock")]
  public static extern void swig_logger_base_on_onblock(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_onblockSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_onblockSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_applied_transaction")]
  public static extern void swig_logger_base_on_applied_transaction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_applied_transactionSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_applied_transactionSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_add_ram_correction")]
  public static extern void swig_logger_base_on_add_ram_correction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_add_ram_correctionSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_add_ram_correctionSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_input_action")]
  public static extern void swig_logger_base_on_input_action(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_input_actionSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_input_actionSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_require_recipient")]
  public static extern void swig_logger_base_on_require_recipient(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_require_recipientSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_require_recipientSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_send_inline")]
  public static extern void swig_logger_base_on_send_inline(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_send_inlineSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_send_inlineSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_send_context_free_inline")]
  public static extern void swig_logger_base_on_send_context_free_inline(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_send_context_free_inlineSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_send_context_free_inlineSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_cancel_deferred")]
  public static extern void swig_logger_base_on_cancel_deferred(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_cancel_deferredSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_cancel_deferredSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_send_deferred")]
  public static extern void swig_logger_base_on_send_deferred(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_send_deferredSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_send_deferredSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_create_deferred")]
  public static extern void swig_logger_base_on_create_deferred(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_create_deferredSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_create_deferredSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_fail_deferred")]
  public static extern void swig_logger_base_on_fail_deferred(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_fail_deferredSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_fail_deferredSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_create_table")]
  public static extern void swig_logger_base_on_create_table(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_create_tableSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_create_tableSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_remove_table")]
  public static extern void swig_logger_base_on_remove_table(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_remove_tableSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_remove_tableSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_db_store_i64")]
  public static extern void swig_logger_base_on_db_store_i64(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_db_store_i64SwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_db_store_i64SwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_db_update_i64")]
  public static extern void swig_logger_base_on_db_update_i64(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_db_update_i64SwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_db_update_i64SwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_db_remove_i64")]
  public static extern void swig_logger_base_on_db_remove_i64(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_db_remove_i64SwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_db_remove_i64SwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_ram_event")]
  public static extern void swig_logger_base_on_ram_event(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_ram_eventSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_ram_eventSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_create_permission")]
  public static extern void swig_logger_base_on_create_permission(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_create_permissionSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_create_permissionSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_modify_permission")]
  public static extern void swig_logger_base_on_modify_permission(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_modify_permissionSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_modify_permissionSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_remove_permission")]
  public static extern void swig_logger_base_on_remove_permission(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_on_remove_permissionSwigExplicitswig_logger_base")]
  public static extern void swig_logger_base_on_remove_permissionSwigExplicitswig_logger_base(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_swig_logger_base")]
  public static extern global::System.IntPtr new_swig_logger_base();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_swig_logger_base_director_connect")]
  public static extern void swig_logger_base_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, swig_logger_base.SwigDelegateswig_logger_base_0 delegate0, swig_logger_base.SwigDelegateswig_logger_base_1 delegate1, swig_logger_base.SwigDelegateswig_logger_base_2 delegate2, swig_logger_base.SwigDelegateswig_logger_base_3 delegate3, swig_logger_base.SwigDelegateswig_logger_base_4 delegate4, swig_logger_base.SwigDelegateswig_logger_base_5 delegate5, swig_logger_base.SwigDelegateswig_logger_base_6 delegate6, swig_logger_base.SwigDelegateswig_logger_base_7 delegate7, swig_logger_base.SwigDelegateswig_logger_base_8 delegate8, swig_logger_base.SwigDelegateswig_logger_base_9 delegate9, swig_logger_base.SwigDelegateswig_logger_base_10 delegate10, swig_logger_base.SwigDelegateswig_logger_base_11 delegate11, swig_logger_base.SwigDelegateswig_logger_base_12 delegate12, swig_logger_base.SwigDelegateswig_logger_base_13 delegate13, swig_logger_base.SwigDelegateswig_logger_base_14 delegate14, swig_logger_base.SwigDelegateswig_logger_base_15 delegate15, swig_logger_base.SwigDelegateswig_logger_base_16 delegate16, swig_logger_base.SwigDelegateswig_logger_base_17 delegate17, swig_logger_base.SwigDelegateswig_logger_base_18 delegate18, swig_logger_base.SwigDelegateswig_logger_base_19 delegate19, swig_logger_base.SwigDelegateswig_logger_base_20 delegate20, swig_logger_base.SwigDelegateswig_logger_base_21 delegate21, swig_logger_base.SwigDelegateswig_logger_base_22 delegate22, swig_logger_base.SwigDelegateswig_logger_base_23 delegate23, swig_logger_base.SwigDelegateswig_logger_base_24 delegate24, swig_logger_base.SwigDelegateswig_logger_base_25 delegate25, swig_logger_base.SwigDelegateswig_logger_base_26 delegate26, swig_logger_base.SwigDelegateswig_logger_base_27 delegate27);
}
