//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class NodeosSwigModulePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="SWIGRegisterExceptionCallbacks_NodeosSwigModule")]
    public static extern void SWIGRegisterExceptionCallbacks_NodeosSwigModule(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_NodeosSwigModule")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_NodeosSwigModule(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_NodeosSwigModule(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_NodeosSwigModule(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="SWIGRegisterStringCallback_NodeosSwigModule")]
    public static extern void SWIGRegisterStringCallback_NodeosSwigModule(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_NodeosSwigModule(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static NodeosSwigModulePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_p_int")]
  public static extern global::System.IntPtr new_p_int();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_copy_p_int")]
  public static extern global::System.IntPtr copy_p_int(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_p_int")]
  public static extern void delete_p_int(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_int_assign")]
  public static extern void p_int_assign(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_int_value")]
  public static extern int p_int_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_p_long_long")]
  public static extern global::System.IntPtr new_p_long_long();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_copy_p_long_long")]
  public static extern global::System.IntPtr copy_p_long_long(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_p_long_long")]
  public static extern void delete_p_long_long(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_long_long_assign")]
  public static extern void p_long_long_assign(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_long_long_value")]
  public static extern long p_long_long_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_p_short")]
  public static extern global::System.IntPtr new_p_short();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_copy_p_short")]
  public static extern global::System.IntPtr copy_p_short(short jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_p_short")]
  public static extern void delete_p_short(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_short_assign")]
  public static extern void p_short_assign(global::System.Runtime.InteropServices.HandleRef jarg1, short jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_short_value")]
  public static extern short p_short_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_p_signed_char")]
  public static extern global::System.IntPtr new_p_signed_char();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_copy_p_signed_char")]
  public static extern global::System.IntPtr copy_p_signed_char(sbyte jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_p_signed_char")]
  public static extern void delete_p_signed_char(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_signed_char_assign")]
  public static extern void p_signed_char_assign(global::System.Runtime.InteropServices.HandleRef jarg1, sbyte jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_signed_char_value")]
  public static extern sbyte p_signed_char_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_p_uint")]
  public static extern global::System.IntPtr new_p_uint();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_copy_p_uint")]
  public static extern global::System.IntPtr copy_p_uint(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_p_uint")]
  public static extern void delete_p_uint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_uint_assign")]
  public static extern void p_uint_assign(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_uint_value")]
  public static extern uint p_uint_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_p_unsigned_char")]
  public static extern global::System.IntPtr new_p_unsigned_char();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_copy_p_unsigned_char")]
  public static extern global::System.IntPtr copy_p_unsigned_char(byte jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_p_unsigned_char")]
  public static extern void delete_p_unsigned_char(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_unsigned_char_assign")]
  public static extern void p_unsigned_char_assign(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_unsigned_char_value")]
  public static extern byte p_unsigned_char_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_p_unsigned_int")]
  public static extern global::System.IntPtr new_p_unsigned_int();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_copy_p_unsigned_int")]
  public static extern global::System.IntPtr copy_p_unsigned_int(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_p_unsigned_int")]
  public static extern void delete_p_unsigned_int(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_unsigned_int_assign")]
  public static extern void p_unsigned_int_assign(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_unsigned_int_value")]
  public static extern uint p_unsigned_int_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_p_unsigned_long_long")]
  public static extern global::System.IntPtr new_p_unsigned_long_long();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_copy_p_unsigned_long_long")]
  public static extern global::System.IntPtr copy_p_unsigned_long_long(ulong jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_p_unsigned_long_long")]
  public static extern void delete_p_unsigned_long_long(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_unsigned_long_long_assign")]
  public static extern void p_unsigned_long_long_assign(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_unsigned_long_long_value")]
  public static extern ulong p_unsigned_long_long_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_p_unsigned_short")]
  public static extern global::System.IntPtr new_p_unsigned_short();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_copy_p_unsigned_short")]
  public static extern global::System.IntPtr copy_p_unsigned_short(ushort jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_p_unsigned_short")]
  public static extern void delete_p_unsigned_short(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_unsigned_short_assign")]
  public static extern void p_unsigned_short_assign(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_p_unsigned_short_value")]
  public static extern ushort p_unsigned_short_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigDataWrapper_data_set")]
  public static extern void SwigDataWrapper_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigDataWrapper_data_get")]
  public static extern global::System.IntPtr SwigDataWrapper_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigDataWrapper_size_set")]
  public static extern void SwigDataWrapper_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigDataWrapper_size_get")]
  public static extern int SwigDataWrapper_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_SwigDataWrapper")]
  public static extern global::System.IntPtr new_SwigDataWrapper(string jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_SwigDataWrapper")]
  public static extern void delete_SwigDataWrapper(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_SwigLoggerBase")]
  public static extern void delete_SwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnDeepMindVersion")]
  public static extern void SwigLoggerBase_OnDeepMindVersion(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnDeepMindVersionSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnDeepMindVersionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAbidumpStart")]
  public static extern void SwigLoggerBase_OnAbidumpStart(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAbidumpStartSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnAbidumpStartSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAbidumpAbi")]
  public static extern void SwigLoggerBase_OnAbidumpAbi(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAbidumpAbiSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnAbidumpAbiSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAbidumpEnd")]
  public static extern void SwigLoggerBase_OnAbidumpEnd(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAbidumpEndSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnAbidumpEndSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnStartBlock")]
  public static extern void SwigLoggerBase_OnStartBlock(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnStartBlockSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnStartBlockSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAcceptedBlock")]
  public static extern void SwigLoggerBase_OnAcceptedBlock(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAcceptedBlockSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnAcceptedBlockSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnSwitchForks")]
  public static extern void SwigLoggerBase_OnSwitchForks(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnSwitchForksSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnSwitchForksSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnError")]
  public static extern void SwigLoggerBase_OnError(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnErrorSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnErrorSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnOnblock")]
  public static extern void SwigLoggerBase_OnOnblock(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnOnblockSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnOnblockSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAppliedTransaction")]
  public static extern void SwigLoggerBase_OnAppliedTransaction(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAppliedTransactionSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnAppliedTransactionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAddRamCorrection")]
  public static extern void SwigLoggerBase_OnAddRamCorrection(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, string jarg4, ulong jarg5, ulong jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnAddRamCorrectionSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnAddRamCorrectionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, string jarg4, ulong jarg5, ulong jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnInputAction")]
  public static extern void SwigLoggerBase_OnInputAction(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnInputActionSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnInputActionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnRequireRecipient")]
  public static extern void SwigLoggerBase_OnRequireRecipient(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnRequireRecipientSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnRequireRecipientSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnSendInline")]
  public static extern void SwigLoggerBase_OnSendInline(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnSendInlineSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnSendInlineSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnSendContextFreeInline")]
  public static extern void SwigLoggerBase_OnSendContextFreeInline(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnSendContextFreeInlineSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnSendContextFreeInlineSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnCancelDeferred")]
  public static extern void SwigLoggerBase_OnCancelDeferred(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnCancelDeferredSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnCancelDeferredSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnSendDeferred")]
  public static extern void SwigLoggerBase_OnSendDeferred(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnSendDeferredSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnSendDeferredSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnCreateDeferred")]
  public static extern void SwigLoggerBase_OnCreateDeferred(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnCreateDeferredSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnCreateDeferredSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, uint jarg3, ulong jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, ulong jarg6, uint jarg7, uint jarg8, uint jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnFailDeferred")]
  public static extern void SwigLoggerBase_OnFailDeferred(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnFailDeferredSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnFailDeferredSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnCreateTable")]
  public static extern void SwigLoggerBase_OnCreateTable(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnCreateTableSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnCreateTableSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnRemoveTable")]
  public static extern void SwigLoggerBase_OnRemoveTable(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnRemoveTableSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnRemoveTableSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnDbStoreI64")]
  public static extern void SwigLoggerBase_OnDbStoreI64(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnDbStoreI64SwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnDbStoreI64SwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnDbUpdateI64")]
  public static extern void SwigLoggerBase_OnDbUpdateI64(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnDbUpdateI64SwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnDbUpdateI64SwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnDbRemoveI64")]
  public static extern void SwigLoggerBase_OnDbRemoveI64(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnDbRemoveI64SwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnDbRemoveI64SwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ulong jarg3, ulong jarg4, ulong jarg5, ulong jarg6, ulong jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnRamEvent")]
  public static extern void SwigLoggerBase_OnRamEvent(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, string jarg3, string jarg4, string jarg5, string jarg6, ulong jarg7, ulong jarg8, long jarg9);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnRamEventSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnRamEventSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, string jarg3, string jarg4, string jarg5, string jarg6, ulong jarg7, ulong jarg8, long jarg9);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnCreatePermission")]
  public static extern void SwigLoggerBase_OnCreatePermission(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnCreatePermissionSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnCreatePermissionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnModifyPermission")]
  public static extern void SwigLoggerBase_OnModifyPermission(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnModifyPermissionSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnModifyPermissionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnRemovePermission")]
  public static extern void SwigLoggerBase_OnRemovePermission(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_OnRemovePermissionSwigExplicitSwigLoggerBase")]
  public static extern void SwigLoggerBase_OnRemovePermissionSwigExplicitSwigLoggerBase(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_SwigLoggerBase")]
  public static extern global::System.IntPtr new_SwigLoggerBase();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_SwigLoggerBase_director_connect")]
  public static extern void SwigLoggerBase_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, SwigLoggerBase.SwigDelegateSwigLoggerBase_0 delegate0, SwigLoggerBase.SwigDelegateSwigLoggerBase_1 delegate1, SwigLoggerBase.SwigDelegateSwigLoggerBase_2 delegate2, SwigLoggerBase.SwigDelegateSwigLoggerBase_3 delegate3, SwigLoggerBase.SwigDelegateSwigLoggerBase_4 delegate4, SwigLoggerBase.SwigDelegateSwigLoggerBase_5 delegate5, SwigLoggerBase.SwigDelegateSwigLoggerBase_6 delegate6, SwigLoggerBase.SwigDelegateSwigLoggerBase_7 delegate7, SwigLoggerBase.SwigDelegateSwigLoggerBase_8 delegate8, SwigLoggerBase.SwigDelegateSwigLoggerBase_9 delegate9, SwigLoggerBase.SwigDelegateSwigLoggerBase_10 delegate10, SwigLoggerBase.SwigDelegateSwigLoggerBase_11 delegate11, SwigLoggerBase.SwigDelegateSwigLoggerBase_12 delegate12, SwigLoggerBase.SwigDelegateSwigLoggerBase_13 delegate13, SwigLoggerBase.SwigDelegateSwigLoggerBase_14 delegate14, SwigLoggerBase.SwigDelegateSwigLoggerBase_15 delegate15, SwigLoggerBase.SwigDelegateSwigLoggerBase_16 delegate16, SwigLoggerBase.SwigDelegateSwigLoggerBase_17 delegate17, SwigLoggerBase.SwigDelegateSwigLoggerBase_18 delegate18, SwigLoggerBase.SwigDelegateSwigLoggerBase_19 delegate19, SwigLoggerBase.SwigDelegateSwigLoggerBase_20 delegate20, SwigLoggerBase.SwigDelegateSwigLoggerBase_21 delegate21, SwigLoggerBase.SwigDelegateSwigLoggerBase_22 delegate22, SwigLoggerBase.SwigDelegateSwigLoggerBase_23 delegate23, SwigLoggerBase.SwigDelegateSwigLoggerBase_24 delegate24, SwigLoggerBase.SwigDelegateSwigLoggerBase_25 delegate25, SwigLoggerBase.SwigDelegateSwigLoggerBase_26 delegate26, SwigLoggerBase.SwigDelegateSwigLoggerBase_27 delegate27);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Clear")]
  public static extern void StringVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Add")]
  public static extern void StringVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Size")]
  public static extern uint StringVector_Size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Capacity")]
  public static extern uint StringVector_Capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Reserve")]
  public static extern void StringVector_Reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_StringVector__SWIG_0")]
  public static extern global::System.IntPtr new_StringVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_StringVector__SWIG_1")]
  public static extern global::System.IntPtr new_StringVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_StringVector__SWIG_2")]
  public static extern global::System.IntPtr new_StringVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Getitemcopy")]
  public static extern string StringVector_Getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Getitem")]
  public static extern string StringVector_Getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Setitem")]
  public static extern void StringVector_Setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_AddRange")]
  public static extern void StringVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_GetRange")]
  public static extern global::System.IntPtr StringVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Insert")]
  public static extern void StringVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_InsertRange")]
  public static extern void StringVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_RemoveAt")]
  public static extern void StringVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_RemoveRange")]
  public static extern void StringVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Repeat")]
  public static extern global::System.IntPtr StringVector_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Reverse__SWIG_0")]
  public static extern void StringVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Reverse__SWIG_1")]
  public static extern void StringVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_SetRange")]
  public static extern void StringVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Contains")]
  public static extern bool StringVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_IndexOf")]
  public static extern int StringVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_LastIndexOf")]
  public static extern int StringVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_StringVector_Remove")]
  public static extern bool StringVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_StringVector")]
  public static extern void delete_StringVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_NodeosSwig_StartNodeos")]
  public static extern void NodeosSwig_StartNodeos(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_NodeosSwig_Start")]
  public static extern int NodeosSwig_Start(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_new_NodeosSwig")]
  public static extern global::System.IntPtr new_NodeosSwig();

  [global::System.Runtime.InteropServices.DllImport("nodeos_swig", EntryPoint="CSharp_delete_NodeosSwig")]
  public static extern void delete_NodeosSwig(global::System.Runtime.InteropServices.HandleRef jarg1);
}
