/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_NodeosSwigModule_WRAP_H_
#define SWIG_NodeosSwigModule_WRAP_H_

class SwigDirector_SwigLoggerBase : public swig_logger_base, public Swig::Director {

public:
    SwigDirector_SwigLoggerBase();
    virtual ~SwigDirector_SwigLoggerBase();
    virtual void on_deep_mind_version(std::string name, uint32_t major, uint32_t minor);
    virtual void on_abidump_start(uint32_t block_num, uint64_t global_sequence_num);
    virtual void on_abidump_abi(uint64_t name, swig_data_wrapper abi_data);
    virtual void on_abidump_end();
    virtual void on_start_block(uint32_t start_block);
    virtual void on_accepted_block(uint32_t num, swig_data_wrapper blk);
    virtual void on_switch_forks(swig_data_wrapper from_id, swig_data_wrapper to_id);
    virtual void on_error(swig_data_wrapper id, swig_data_wrapper trx);
    virtual void on_onblock(swig_data_wrapper id, swig_data_wrapper trx);
    virtual void on_applied_transaction(uint32_t block_num, swig_data_wrapper traces);
    virtual void on_add_ram_correction(uint32_t action_id, int64_t correction_id, std::string event_id, uint64_t payer, uint64_t delta);
    virtual void on_input_action(uint32_t action_id);
    virtual void on_require_recipient(uint32_t action_id);
    virtual void on_send_inline(uint32_t action_id);
    virtual void on_send_context_free_inline(uint32_t action_id);
    virtual void on_cancel_deferred(uint8_t qual, uint32_t action_id, uint64_t sender, swig_data_wrapper sender_id, uint64_t payer, uint32_t published, uint32_t delay, uint32_t expiration, swig_data_wrapper trx_id, swig_data_wrapper trx);
    virtual void on_send_deferred(uint8_t qual, uint32_t action_id, uint64_t sender, swig_data_wrapper sender_id, uint64_t payer, uint32_t published, uint32_t delay, uint32_t expiration, swig_data_wrapper trx_id, swig_data_wrapper trx);
    virtual void on_create_deferred(uint8_t qual, uint32_t action_id, uint64_t sender, swig_data_wrapper sender_id, uint64_t payer, uint32_t published, uint32_t delay, uint32_t expiration, swig_data_wrapper trx_id, swig_data_wrapper trx);
    virtual void on_fail_deferred(uint32_t action_id);
    virtual void on_create_table(uint32_t action_id, uint64_t code, uint64_t scope, uint64_t table, uint64_t payer);
    virtual void on_remove_table(uint32_t action_id, uint64_t code, uint64_t scope, uint64_t table, uint64_t payer);
    virtual void on_db_store_i64(uint32_t action_id, uint64_t payer, uint64_t table_code, uint64_t scope, uint64_t table_name, uint64_t primkey, swig_data_wrapper ndata);
    virtual void on_db_update_i64(uint32_t action_id, uint64_t payer, uint64_t table_code, uint64_t scope, uint64_t table_name, uint64_t primkey, swig_data_wrapper odata, swig_data_wrapper ndata);
    virtual void on_db_remove_i64(uint32_t action_id, uint64_t payer, uint64_t table_code, uint64_t scope, uint64_t table_name, uint64_t primkey, swig_data_wrapper odata);
    virtual void on_ram_event(uint32_t action_id, std::string event_id, std::string family, std::string operation, std::string legacy_tag, uint64_t payer, uint64_t new_usage, int64_t delta);
    virtual void on_create_permission(uint32_t action_id, int64_t permission_id, swig_data_wrapper data);
    virtual void on_modify_permission(uint32_t action_id, int64_t permission_id, swig_data_wrapper opdata, swig_data_wrapper npdata);
    virtual void on_remove_permission(uint32_t action_id, int64_t permission_id, swig_data_wrapper data);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(char *, unsigned int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(unsigned int, unsigned long long);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(unsigned long long, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(unsigned int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)(unsigned int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(unsigned int, long long, char *, unsigned long long, unsigned long long);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(unsigned char, unsigned int, unsigned long long, void *, unsigned long long, unsigned int, unsigned int, unsigned int, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(unsigned char, unsigned int, unsigned long long, void *, unsigned long long, unsigned int, unsigned int, unsigned int, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback17_t)(unsigned char, unsigned int, unsigned long long, void *, unsigned long long, unsigned int, unsigned int, unsigned int, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback18_t)(unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(unsigned int, unsigned long long, unsigned long long, unsigned long long, unsigned long long);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(unsigned int, unsigned long long, unsigned long long, unsigned long long, unsigned long long);
    typedef void (SWIGSTDCALL* SWIG_Callback21_t)(unsigned int, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback22_t)(unsigned int, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback23_t)(unsigned int, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback24_t)(unsigned int, char *, char *, char *, char *, unsigned long long, unsigned long long, long long);
    typedef void (SWIGSTDCALL* SWIG_Callback25_t)(unsigned int, long long, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback26_t)(unsigned int, long long, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback27_t)(unsigned int, long long, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnDeepMindVersion, SWIG_Callback1_t callbackOnAbidumpStart, SWIG_Callback2_t callbackOnAbidumpAbi, SWIG_Callback3_t callbackOnAbidumpEnd, SWIG_Callback4_t callbackOnStartBlock, SWIG_Callback5_t callbackOnAcceptedBlock, SWIG_Callback6_t callbackOnSwitchForks, SWIG_Callback7_t callbackOnError, SWIG_Callback8_t callbackOnOnblock, SWIG_Callback9_t callbackOnAppliedTransaction, SWIG_Callback10_t callbackOnAddRamCorrection, SWIG_Callback11_t callbackOnInputAction, SWIG_Callback12_t callbackOnRequireRecipient, SWIG_Callback13_t callbackOnSendInline, SWIG_Callback14_t callbackOnSendContextFreeInline, SWIG_Callback15_t callbackOnCancelDeferred, SWIG_Callback16_t callbackOnSendDeferred, SWIG_Callback17_t callbackOnCreateDeferred, SWIG_Callback18_t callbackOnFailDeferred, SWIG_Callback19_t callbackOnCreateTable, SWIG_Callback20_t callbackOnRemoveTable, SWIG_Callback21_t callbackOnDbStoreI64, SWIG_Callback22_t callbackOnDbUpdateI64, SWIG_Callback23_t callbackOnDbRemoveI64, SWIG_Callback24_t callbackOnRamEvent, SWIG_Callback25_t callbackOnCreatePermission, SWIG_Callback26_t callbackOnModifyPermission, SWIG_Callback27_t callbackOnRemovePermission);

private:
    SWIG_Callback0_t swig_callbackOnDeepMindVersion;
    SWIG_Callback1_t swig_callbackOnAbidumpStart;
    SWIG_Callback2_t swig_callbackOnAbidumpAbi;
    SWIG_Callback3_t swig_callbackOnAbidumpEnd;
    SWIG_Callback4_t swig_callbackOnStartBlock;
    SWIG_Callback5_t swig_callbackOnAcceptedBlock;
    SWIG_Callback6_t swig_callbackOnSwitchForks;
    SWIG_Callback7_t swig_callbackOnError;
    SWIG_Callback8_t swig_callbackOnOnblock;
    SWIG_Callback9_t swig_callbackOnAppliedTransaction;
    SWIG_Callback10_t swig_callbackOnAddRamCorrection;
    SWIG_Callback11_t swig_callbackOnInputAction;
    SWIG_Callback12_t swig_callbackOnRequireRecipient;
    SWIG_Callback13_t swig_callbackOnSendInline;
    SWIG_Callback14_t swig_callbackOnSendContextFreeInline;
    SWIG_Callback15_t swig_callbackOnCancelDeferred;
    SWIG_Callback16_t swig_callbackOnSendDeferred;
    SWIG_Callback17_t swig_callbackOnCreateDeferred;
    SWIG_Callback18_t swig_callbackOnFailDeferred;
    SWIG_Callback19_t swig_callbackOnCreateTable;
    SWIG_Callback20_t swig_callbackOnRemoveTable;
    SWIG_Callback21_t swig_callbackOnDbStoreI64;
    SWIG_Callback22_t swig_callbackOnDbUpdateI64;
    SWIG_Callback23_t swig_callbackOnDbRemoveI64;
    SWIG_Callback24_t swig_callbackOnRamEvent;
    SWIG_Callback25_t swig_callbackOnCreatePermission;
    SWIG_Callback26_t swig_callbackOnModifyPermission;
    SWIG_Callback27_t swig_callbackOnRemovePermission;
    void swig_init_callbacks();
};


#endif
