//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class NodeosSwigModule {
  public static SWIGTYPE_p_int new_p_int() {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.new_p_int();
    SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_int copy_p_int(int value) {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.copy_p_int(value);
    SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    return ret;
  }

  public static void delete_p_int(SWIGTYPE_p_int obj) {
    NodeosSwigModulePINVOKE.delete_p_int(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static void p_int_assign(SWIGTYPE_p_int obj, int value) {
    NodeosSwigModulePINVOKE.p_int_assign(SWIGTYPE_p_int.getCPtr(obj), value);
  }

  public static int p_int_value(SWIGTYPE_p_int obj) {
    int ret = NodeosSwigModulePINVOKE.p_int_value(SWIGTYPE_p_int.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_long_long new_p_long_long() {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.new_p_long_long();
    SWIGTYPE_p_long_long ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_long_long(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_long_long copy_p_long_long(long value) {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.copy_p_long_long(value);
    SWIGTYPE_p_long_long ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_long_long(cPtr, false);
    return ret;
  }

  public static void delete_p_long_long(SWIGTYPE_p_long_long obj) {
    NodeosSwigModulePINVOKE.delete_p_long_long(SWIGTYPE_p_long_long.getCPtr(obj));
  }

  public static void p_long_long_assign(SWIGTYPE_p_long_long obj, long value) {
    NodeosSwigModulePINVOKE.p_long_long_assign(SWIGTYPE_p_long_long.getCPtr(obj), value);
  }

  public static long p_long_long_value(SWIGTYPE_p_long_long obj) {
    long ret = NodeosSwigModulePINVOKE.p_long_long_value(SWIGTYPE_p_long_long.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_short new_p_short() {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.new_p_short();
    SWIGTYPE_p_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_short(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_short copy_p_short(short value) {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.copy_p_short(value);
    SWIGTYPE_p_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_short(cPtr, false);
    return ret;
  }

  public static void delete_p_short(SWIGTYPE_p_short obj) {
    NodeosSwigModulePINVOKE.delete_p_short(SWIGTYPE_p_short.getCPtr(obj));
  }

  public static void p_short_assign(SWIGTYPE_p_short obj, short value) {
    NodeosSwigModulePINVOKE.p_short_assign(SWIGTYPE_p_short.getCPtr(obj), value);
  }

  public static short p_short_value(SWIGTYPE_p_short obj) {
    short ret = NodeosSwigModulePINVOKE.p_short_value(SWIGTYPE_p_short.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_signed_char new_p_signed_char() {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.new_p_signed_char();
    SWIGTYPE_p_signed_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_signed_char(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_signed_char copy_p_signed_char(sbyte value) {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.copy_p_signed_char(value);
    SWIGTYPE_p_signed_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_signed_char(cPtr, false);
    return ret;
  }

  public static void delete_p_signed_char(SWIGTYPE_p_signed_char obj) {
    NodeosSwigModulePINVOKE.delete_p_signed_char(SWIGTYPE_p_signed_char.getCPtr(obj));
  }

  public static void p_signed_char_assign(SWIGTYPE_p_signed_char obj, sbyte value) {
    NodeosSwigModulePINVOKE.p_signed_char_assign(SWIGTYPE_p_signed_char.getCPtr(obj), value);
  }

  public static sbyte p_signed_char_value(SWIGTYPE_p_signed_char obj) {
    sbyte ret = NodeosSwigModulePINVOKE.p_signed_char_value(SWIGTYPE_p_signed_char.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_unsigned_int new_p_uint() {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.new_p_uint();
    SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_unsigned_int copy_p_uint(uint value) {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.copy_p_uint(value);
    SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
    return ret;
  }

  public static void delete_p_uint(SWIGTYPE_p_unsigned_int obj) {
    NodeosSwigModulePINVOKE.delete_p_uint(SWIGTYPE_p_unsigned_int.getCPtr(obj));
  }

  public static void p_uint_assign(SWIGTYPE_p_unsigned_int obj, uint value) {
    NodeosSwigModulePINVOKE.p_uint_assign(SWIGTYPE_p_unsigned_int.getCPtr(obj), value);
  }

  public static uint p_uint_value(SWIGTYPE_p_unsigned_int obj) {
    uint ret = NodeosSwigModulePINVOKE.p_uint_value(SWIGTYPE_p_unsigned_int.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_unsigned_char new_p_unsigned_char() {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.new_p_unsigned_char();
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_unsigned_char copy_p_unsigned_char(byte value) {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.copy_p_unsigned_char(value);
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public static void delete_p_unsigned_char(SWIGTYPE_p_unsigned_char obj) {
    NodeosSwigModulePINVOKE.delete_p_unsigned_char(SWIGTYPE_p_unsigned_char.getCPtr(obj));
  }

  public static void p_unsigned_char_assign(SWIGTYPE_p_unsigned_char obj, byte value) {
    NodeosSwigModulePINVOKE.p_unsigned_char_assign(SWIGTYPE_p_unsigned_char.getCPtr(obj), value);
  }

  public static byte p_unsigned_char_value(SWIGTYPE_p_unsigned_char obj) {
    byte ret = NodeosSwigModulePINVOKE.p_unsigned_char_value(SWIGTYPE_p_unsigned_char.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_unsigned_int new_p_unsigned_int() {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.new_p_unsigned_int();
    SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_unsigned_int copy_p_unsigned_int(uint value) {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.copy_p_unsigned_int(value);
    SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
    return ret;
  }

  public static void delete_p_unsigned_int(SWIGTYPE_p_unsigned_int obj) {
    NodeosSwigModulePINVOKE.delete_p_unsigned_int(SWIGTYPE_p_unsigned_int.getCPtr(obj));
  }

  public static void p_unsigned_int_assign(SWIGTYPE_p_unsigned_int obj, uint value) {
    NodeosSwigModulePINVOKE.p_unsigned_int_assign(SWIGTYPE_p_unsigned_int.getCPtr(obj), value);
  }

  public static uint p_unsigned_int_value(SWIGTYPE_p_unsigned_int obj) {
    uint ret = NodeosSwigModulePINVOKE.p_unsigned_int_value(SWIGTYPE_p_unsigned_int.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_unsigned_long_long new_p_unsigned_long_long() {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.new_p_unsigned_long_long();
    SWIGTYPE_p_unsigned_long_long ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_unsigned_long_long copy_p_unsigned_long_long(ulong value) {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.copy_p_unsigned_long_long(value);
    SWIGTYPE_p_unsigned_long_long ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
    return ret;
  }

  public static void delete_p_unsigned_long_long(SWIGTYPE_p_unsigned_long_long obj) {
    NodeosSwigModulePINVOKE.delete_p_unsigned_long_long(SWIGTYPE_p_unsigned_long_long.getCPtr(obj));
  }

  public static void p_unsigned_long_long_assign(SWIGTYPE_p_unsigned_long_long obj, ulong value) {
    NodeosSwigModulePINVOKE.p_unsigned_long_long_assign(SWIGTYPE_p_unsigned_long_long.getCPtr(obj), value);
  }

  public static ulong p_unsigned_long_long_value(SWIGTYPE_p_unsigned_long_long obj) {
    ulong ret = NodeosSwigModulePINVOKE.p_unsigned_long_long_value(SWIGTYPE_p_unsigned_long_long.getCPtr(obj));
    return ret;
  }

  public static SWIGTYPE_p_unsigned_short new_p_unsigned_short() {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.new_p_unsigned_short();
    SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
    return ret;
  }

  public static SWIGTYPE_p_unsigned_short copy_p_unsigned_short(ushort value) {
    global::System.IntPtr cPtr = NodeosSwigModulePINVOKE.copy_p_unsigned_short(value);
    SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
    return ret;
  }

  public static void delete_p_unsigned_short(SWIGTYPE_p_unsigned_short obj) {
    NodeosSwigModulePINVOKE.delete_p_unsigned_short(SWIGTYPE_p_unsigned_short.getCPtr(obj));
  }

  public static void p_unsigned_short_assign(SWIGTYPE_p_unsigned_short obj, ushort value) {
    NodeosSwigModulePINVOKE.p_unsigned_short_assign(SWIGTYPE_p_unsigned_short.getCPtr(obj), value);
  }

  public static ushort p_unsigned_short_value(SWIGTYPE_p_unsigned_short obj) {
    ushort ret = NodeosSwigModulePINVOKE.p_unsigned_short_value(SWIGTYPE_p_unsigned_short.getCPtr(obj));
    return ret;
  }

}
